### ISSUE TITLE
Give deterministic output/order

### ISSUE THREAD

**Issue by egeakman** [EuroPython/programapi#42]
The current version changes the room ordering in the schedule with each run. That should not happen, it should always give the same output as long as the source data doesn't change.

**Comment by artcz** [comment]
One comment on the orders of the room: If we choose to keep the programapi order on the website (instead of re-ordering when rendering the schedule) it makes sense to keep the tutorial rooms in the AEHBCD (or ABEHCD) order instead of alphabetical ABCDEH.
The reason for it is because CD are used for different purposes (workshops, summits) than AEHB (tutorials, different ticket type).

**Comment by egeakman** [comment]
I think we should have a general sorting here (like alphabetical/time/numerical/etc.); and have the year-specific/special ordering on the clients (website/bot).
